version: '3'
services:
  app:
    build:
      context: .
    ports:
      - '5001:5001'
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DB=absensi_db
      - MYSQL_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=absensi_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  phpmyadmin_db:
    image: phpmyadmin:latest
    ports:
      - '8081:80'
    links:
      - db
